# Generated by Django 3.0.1 on 2019-12-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191226_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=20, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
