# Generated by Django 3.0.1 on 2019-12-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191228_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
