# Generated by Django 3.0.1 on 2019-12-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191228_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
